init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

environment:
  nodejs_version: "10.10.0"

cache:
  - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # install latest dotnet core sdk
  - cmd: choco install dotnet-6.0-sdk
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version

os: Visual Studio 2022

build_script:
  - cmd: build.cmd Build
  - cmd: npm test
  - cmd: npm run test:nagareyama

test: off
